
language: node_js
node_js:
- "10"
install:
- npm i
script:
- npm run build-front
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: 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   # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: client/build
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: npm run deploy
    on:
      branch: master

